services:
  # 数据库服务 (db)
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: quant_db_timescale
    ports:
      - "5432:5432"
    environment:
      # 重要：将数据库连接信息从 .env 文件注入，而不是硬编码
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data # 使用具名数据卷，更安全
    # 健康检查，确保应用启动前数据库已就绪
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 应用服务 (app)
  app:
    # build: . 表示使用当前目录下的 Dockerfile 来构建镜像
    build: .
    container_name: quant_app_streamlit
    ports:
      - "8501:8501"
    # 从 .env 文件加载所有环境变量
    env_file:
      - .env
    # 卷挂载：将本地代码目录挂载到容器内，实现代码热更新
    volumes:
      - .:/app
    # depends_on: 确保 app 服务在 db 服务健康后才启动
    depends_on:
      db:
        condition: service_healthy

volumes:
  # 定义一个具名数据卷来持久化数据库数据
  pgdata: